### ISSUE TITLE
[PE-D][Tester C] Sort jumbles the listing

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-4/tp#100]
**What**: The applicant's listing gets jumbled after sorting.

**How**:
1. Run with fresh setup (no existing json data file)
2. Send command  `sort ca1`
3. List

##### Before sort

![image.png](https://raw.githubusercontent.com/ys112/ped/main/files/8df933df-8bc1-42c0-81b3-cc51c38c9185.png)

##### After sort (at step 3)

![image.png](https://raw.githubusercontent.com/ys112/ped/main/files/f483e09d-9c44-4952-b099-62813d624580.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: ys112/ped#8

**Comment by amanzainal** [comment]
I'm not sure if this is a bug (Since "list" is not explicitly defined to be in chronological order, so any random list is still a valid output).

Not sure what the appropriate fix is or if a fix is required / would be considered a feature change, let me know if you guys have any suggestions
