### ISSUE TITLE
[PE-D][Tester C] Sort command accepts other punctuations

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-4/tp#102]
**What**: The sort command goes through without any tests related keywords given, causing 0 students to list and perhaps might be better to show error informing user of a typo in command.

**How**: 
1. Input `sort .r`
2. 0 students listed in feedback message to user

#### Message indicating 0 students listed
![image.png](https://raw.githubusercontent.com/ys112/ped/main/files/7096d81d-ad6d-40b6-8004-ae092f5eee6d.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ys112/ped#10

**Comment by amanzainal** [comment]
Intended fix: sort keywords should mirror grade testName restrictions
