### ISSUE TITLE
[PE-D][Tester A] Duplicate delete feature in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-4/tp#103]
![image.png](https://raw.githubusercontent.com/leepoeaik/ped/main/files/4c622862-0e26-4e6e-9abf-e3eb65e4ca29.png)

Multiple delete section in user guide, and the content does not match.

I'm assuming that the first delete is suppose to be sort, but sort is nowhere to be found in the user guide

![image.png](https://raw.githubusercontent.com/leepoeaik/ped/main/files/4e933ad8-529a-4c0c-ac19-9247bfbb280e.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: leepoeaik/ped#7

**Comment by amanzainal** [comment]
Issue fixed in v1.3 and latest UG
