### ISSUE TITLE
[PE-D][Tester C] Adding of multiple timeslots causes error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-4/tp#108]
**What**: In the given data upon fresh start, Alex Yeoh has only 1 timing. Upon attempting to add another timing, the app shows error which deviates from deviates from what is stated in the user guide; The ability to have multiple timings.

**How**: 
1. Send command `edit 1 !t`
2. Modify values to `edit 1 timeslot: Saturday 3pm-5pm, Monday 1pm-2pm` which should add one more timeslot
2. Error message about timeslot format displayed.

#### Error displayed
![image.png](https://raw.githubusercontent.com/ys112/ped/main/files/baabbf8a-597d-4d36-abef-ff96a091c42e.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ys112/ped#14

**Comment by amanzainal** [comment]
"edit" can be used to delete/modify existing timeslots but not adding new timeslots

**Comment by yap-zong-xin** [comment]
@amanzainal I was able to add/delete/modify timeslots from my end.. Can u help me check if its working at your end when you are free, thanks!

**Comment by joelgoh1** [comment]
This is caused by changes I made in editCommandParser to how grades and timeslots are parsed: 
            ```
if (!Grade.isValidGrade(trimmedGradeString)) {
                throw new ParseException(Timeslots.MESSAGE_CONSTRAINTS);
            } 
            if (!Timeslots.isValidTimeslot(trimmedTimeslotString)) {
                throw new ParseException(Timeslots.MESSAGE_CONSTRAINTS);
            }
```
            
Previously without this line, if you were to edit using an invalid timeslot, it wouldn't show any message, but like it wouldn't accept it either. I think we just need to move the check for isValidGrade and isValidTimeslot in this loop instead
```
          String[] timeslotArray = trimmedTimeslotString.split(",");
            for (String timeslot : timeslotArray) {
                timeslotSet.add(new Timeslots(timeslot.trim()));
            }
```

**Comment by yap-zong-xin** [comment]
@joelgoh1 Ohhh, I see! Most likely I had resolved this issue while I was editing other error messages for the edit yesterday. Thanks a lot!
