### ISSUE TITLE
[PE-D][Tester B] Overly restrictive validation of emails 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-4/tp#78]
## Description 
In accordance to RFC 6530, emails with Latin alphabet, Greek Alphabet, Traditional Chinese characters, Japanese Characters etc should be accepted. However, the app only allows alphanumeric characters with very limited special characters

## Steps to reproduce
1. Launch the application for the first time to load initial data. 
2. Run `add n/John Doe p/99999999 e/户用@户用.户用 a/John street, block 123, #01-01`.

## Expected behaviour
To allow the adding!

## Actual behaviour

![image.png](https://raw.githubusercontent.com/lynnetteeee/ped/main/files/5a03fa2c-dc0e-450d-8962-26e06a7878d8.png)

## Reason for severity
It brings users with international emails low convenience when using your application. 

## Ideas
To allow for the checking of number of characters (as you have nicely done so with the domain name), checking for special character "@", but without restricting to alphanumeric. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: lynnetteeee/ped#2

**Comment by joelgoh1** [comment]
I think we don't need to fix this. Specified that only alphanumeric characters are allowed as part of user guide
