### ISSUE TITLE
[PE-D][Tester A] Does not specify format of [g/GRADE]

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-4/tp#87]
![image.png](https://raw.githubusercontent.com/leepoeaik/ped/main/files/9cb22a58-3562-4756-a7d5-f909101f68d7.png)

The only line explaining about [g/GRADE] in the documentation. No further elaboration on the valid or invalid typed of input. 

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: leepoeaik/ped#3

**Comment by joelgoh1** [comment]
Not really a problem though, this isn't telling you how to use the grade parameter.
